title: Julia Clarke # your name (or website title) here
logo: "/images/20824_JH_9922-hoch.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Data Scientist with 4+ years experience in implementing productive Machine learnings models 
  optimizing business processes in After Sales, logistics and increasing sales conversions,<br><br/>
  holding a Master of Science degree from Technical University of Munich.
 <br><br/>

  Currently I am working for BMW and focusing on analytical optimization of campaigns
  by implementing Machine Learning models to personalize our targeting. 
  <br><br>
  <a href="https://www.linkedin.com/in/juliahehl/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
